### ISSUE TITLE
Log allocator mark-compact

### ISSUE THREAD

**Issue by YangZhou1997** [AIFM-sys/AIFM#2]
Hi, 

Very nice code! Just wondering where you implement the log allocator mark-compact scheme, probably running in another thread somehow. But I could find the exact code location. Is it also in `void FarMemManager::gc_cache()`, where you do mark-evacuate for cold entries? 

Here is the text quoted from the paper: near the end of sec5.2

> To free an object, the runtime marks the object as free. AIFM leverages a mark- compact evacuator to achieve a low memory fragmentation ratio, as shown with other copying log allocators [63].

Best,
Yang

**Comment by zainryan** [comment]
Hi Yang,

Thanks for your interest. Marking happens [here](https://github.com/AIFM-sys/AIFM/blob/45b5c837b4ce2d0dc82c643a14dd35107519d4a6/aifm/src/manager.cpp#L414). Compacting is part of the [cold data write-back procedure](https://github.com/AIFM-sys/AIFM/blob/45b5c837b4ce2d0dc82c643a14dd35107519d4a6/aifm/src/manager.cpp#L414) which invokes the[ swap-out method](https://github.com/AIFM-sys/AIFM/blob/45b5c837b4ce2d0dc82c643a14dd35107519d4a6/aifm/src/manager.cpp#L294) on all marked objects; if it [finds out that the object is hot](https://github.com/AIFM-sys/AIFM/blob/45b5c837b4ce2d0dc82c643a14dd35107519d4a6/aifm/src/manager.cpp#L320), it will copy the object into a new location (i.e., compacting) rather than writing back the data to the remote. 

Thanks,
Zain

**Comment by YangZhou1997** [comment]
Hi Zain, 

Thanks for the quick reply! So it sounds that log allocator compaction is mixed with GC evacuation. 

I also notice that in the log selection phase, 
> The evacuator picks logs in FIFO order from the global non-temporal used list, and then picks from the global temporal used list if necessary, to prioritize non-temporal objects. 
Does it mean the log allocation compaction also has such prioritization? 

Best,
Yang

**Comment by zainryan** [comment]
Yes, since it compacts selected logs.

**Comment by YangZhou1997** [comment]
Cool. My puzzle resolved. Thanks!
